### ISSUE TITLE
Error while running server.js

### ISSUE THREAD

**Issue by ramv** [davglass/yui-express#2]
```
TypeError: Cannot read property 'Y' of undefined
at [object Function].render (/usr/local/lib/node/.npm/yui3/0.5.17/package/lib/express.js:311:35)
at ServerResponse.render (/Users/ramv/.node_libraries/express/view.js:282:26)
at ServerResponse.render (/Users/ramv/.node_libraries/express/view.js:292:14)
at Object.<anonymous> (/Users/ramv/Documents/workspace/yui-express/server.js:149:13)
at pass (/Users/ramv/.node_libraries/connect/middleware/router.js:65:27)
at Object.router [as handle] (/Users/ramv/.node_libraries/connect/middleware/router.js:80:10)
at next (/Users/ramv/.node_libraries/connect/index.js:264:23)
at /Users/ramv/.node_libraries/connect/middleware/staticProvider.js:87:21
at node.js:764:9
```

Not sure what I am doing wrong. Can you please give me some pointers?

**Comment by davglass** [comment]
Can you tell me what is the output of this is?
      npm ls installed

**Comment by ramv** [comment]
```
ram-macbooklocal:CheckinAggreator ramv$ npm ls installed
npm info it worked if it ends with ok
npm info using npm@0.2.10
npm info using node@v0.2.0
class@0.3.0               =tjholowaychuk active installed latest remote
connect@0.2.4             =creationix =tjholowaychuk installed remote
connect@0.2.7             =creationix =tjholowaychuk installed remote
connect@0.4.0             =creationix =tjholowaychuk active installed latest remote
connect-auth@0.1.2        =ciaranj installed remote
connect-auth@0.1.3        =ciaranj installed remote
connect-auth@0.2.0        =ciaranj installed remote
connect-auth@0.2.1        =ciaranj installed latest remote
connect-auth@0.2.2        =ciaranj active installed
connect-mongodb@0.0.2     =masylum installed latest remote
connect-mongodb@0.0.3     =masylum active installed
ejs@0.2.0                 =tjholowaychuk installed remote
ejs@0.2.1                 =tjholowaychuk active installed latest remote
express@1.0.0rc2          =tjholowaychuk installed remote
express@1.0.0rc4          =tjholowaychuk installed remote
express@1.0.0             =tjholowaychuk active installed latest remote
express-extras@0.1.0      =davglass active installed latest remote
expresso@0.6.2            =tjholowaychuk active installed remote
ext@0.6.1                 =tjholowaychuk active installed latest remote
git@0.1.0                 =christkv active installed latest remote
htmlparser@1.7.2          =tautologistics active installed latest remote
jsdom@0.1.20              =tmpvar active installed latest remote
jsgi@0.0.1                =nathan active installed remote    
mjsunit.runner@0.1.3      =tmpvar active installed latest remote
mongodb@0.7.9             =christkv active installed latest remote
mongoose@0.0.3            =nw =tmpvar active installed latest remote
node-inspector@0.0.4      =dannycoates active installed remote
nodeunit@0.1.0            =caolan installed remote
nodeunit@0.3.1            =caolan installed remote
nodeunit@0.4.0            =caolan installed remote
nodeunit@0.5.0            =caolan active installed latest remote
nodules@0.1.0             =nathan installed remote
nodules@0.2.1             =nathan active installed latest remote
npm@0.2.10                =isaacs active installed remote
oauth@0.8.3               =ciaranj active installed latest remote
request@0.10.0            =mikeal active installed latest remote
spark@0.1.2               =creationix active installed latest remote
spark2@2.0.7              =davglass active installed latest remote
websocket-server@1.3.03   =miksago active installed remote
yui3@0.5.17               =davglass active installed latest remote
yui3-2in3@0.0.3           =davglass active installed latest remote
yui3-core@2010.11.03      =davglass active installed latest remote
yui3-gallery@2010.09.29   =davglass active installed latest remote
npm ok
```

**Comment by davglass** [comment]
From your error, it looks like you have multiple copies of connect/express installed.

You should look under `~/.node_libraries` and remove connect and express from there.

**Comment by ramv** [comment]
yep that fixed it thanks!
