### ISSUE TITLE
Cannot call method 'set' of null

### ISSUE THREAD

**Issue by chicagoworks** [davglass/yui-express#3]
I've followed the install and setup instructions but get the following error:

TypeError: Cannot call method 'set' of null
    at Object.after (/Users/admin/Sites/yui-express/server.js:172:36)

172:  Y.one('title').set('innerHTML', TITLE);

I've worked around it by adding a <title> tag to the layout_head. Do you have an uncommitted change to the layout_head file or is there something else that I'm missing? Thought or suggestions?

**Comment by rojkov** [comment]
I'm getting a similar error

TypeError: Cannot call method 'set' of null
    at [object Function].render (/home/rozhkov/src/yui-express/node_modules/yui3/lib/yui3-express.js:301:28)
    at Object.<anonymous> (/home/rozhkov/src/yui-express/node_modules/yui3/lib/yui3-express.js:265:24)
    at ServerResponse._render (/home/rozhkov/src/yui-express/node_modules/express/lib/view.js:425:21)
    at ServerResponse.render (/home/rozhkov/src/yui-express/node_modules/express/lib/view.js:318:17)
    at /home/rozhkov/src/yui-express/server.js:161:13
    ...

In my case the failing statement is
eY.one('body').set('innerHTML', content);
and there is no 'body' tag in html templates
